<?php

/**
 * @file
 * Contains recyclebin.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_help().
 */
function recyclebin_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the recyclebin module.
        case 'help.page.recyclebin':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Provide Recycle Bin functionality via state machine API.') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_entity_operation_alter().
 */
function recyclebin_entity_operation_alter(array &$operations, EntityInterface $entity) {
    if (!(\Drupal::currentUser()->hasPermission('access content'))) {
        return;
    }
    //delete node only via recycle bin;
    unset($operations['delete']);
}

/**
 * Implements hook_entity_view_alter().
 */
function recyclebin_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
    if (!(\Drupal::currentUser()->hasPermission('access content'))) {
        return;
    }
    //TODO:: add alter code;
}
