action.configuration.node_set_recycled:
  type: action_configuration_default
  label: 'Push node to recycle bin'

action.configuration.node_set_normal:
  type: action_configuration_default
  label: 'Push node back to normal'